version: "3.8"
services:
  frontend:
    container_name: frontend
    image: frontend_image:1.0
    networks:
      - object-detection
    ports:
      - "8082:8082"
    depends_on:
      - yolo5
      - mongodb

  yolo5:
    container_name: yolo5
    networks:
      - object-detection
    image: yolo_image:5.0
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8081:8081"
  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - object-detection
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  polybot:
    container_name: telegram-bot
    image: polybot_image:3.0
    networks:
      - object-detection
    depends_on:
      - yolo5

volumes:
  mongodb:
    driver: local

networks:
  object-detection:
    name: object-detection
    driver: bridge